routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomepageController::class, 'index'])->name('homepage');

/* Website */
Route::controller(App\Http\Controllers\Website\ArticleController::class)->group(function () {
    Route::prefix('article')->name('article.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/detail/{slug}', 'show')->name('show');
    });
});

Route::controller(App\Http\Controllers\Website\CategoryController::class)->group(function () {
    Route::prefix('category')->name('category.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/detail/{slug}', 'show')->name('show');
    });
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('login/{provider}', [App\Http\Controllers\Auth\LoginController::class, 'redirectToProvider']);
Route::get('{provider}/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleProviderCallback']);

/* CMS */
Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
    /* Category */
    Route::controller(App\Http\Controllers\Admin\CategoryController::class)->middleware(['role:admin,author'])->group(function () {
        Route::prefix('category')->name('category.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/edit/{id}', 'edit')->name('edit');
            Route::get('/detail/{id}', 'show')->name('show');
            Route::get('/datatable', 'datatable')->name('datatable');
            Route::post('/', 'store')->name('store');
            Route::put('/{id}', 'update')->name('update');
            Route::delete('/delete/{id}', 'delete')->name('delete');
        });
    });

    /* Article */
    Route::controller(App\Http\Controllers\Admin\ArticleController::class)->middleware(['role:admin,author'])->group(function () {
        Route::prefix('article')->name('article.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/edit/{id}', 'edit')->name('edit');
            Route::get('/detail/{slug}', 'show')->name('detail');
            Route::get('/datatable', 'datatable')->name('datatable');
            Route::post('/', 'store')->name('store');
            Route::put('/{id}', 'update')->name('update');
            Route::delete('/delete/{id}', 'delete')->name('delete');
        });
    });

    /* User */
    Route::controller(App\Http\Controllers\Admin\UserController::class)->middleware(['role:admin'])->group(function () {
        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/detail/{slug}', 'show')->name('show');
            Route::get('/datatable', 'datatable')->name('datatable');
            Route::post('/', 'store')->name('store');
            Route::put('/{id}', 'update')->name('update');
            Route::delete('/delete/{id}', 'delete')->name('delete');
        });
    });

    Route::put('user/profile/{id}', [App\Http\Controllers\Admin\UserController::class, 'updateProfile'])->name('user.profile.update');
    Route::get('user/profile', [App\Http\Controllers\Admin\UserController::class, 'profile'])->name('user.profile');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['id', 'name', 'slug'];

    /**
     * Get all of the articles for the Category
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function articles()
    {
        return $this->hasMany(Article::class);
    }

    /**
     * Get the article associated with the Category
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function article()
    {
        return $this->hasOne(Article::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Helpers\JsonResponse;
use App\Http\Requests\CategoryRequest;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Str;

class CategoryController extends Controller
{
    protected $categoryService;
    protected $jsonResponse;

    public function __construct(CategoryService $categoryService, JsonResponse $jsonResponse)
    {
        $this->categoryService = $categoryService;
        $this->jsonResponse = $jsonResponse;
    }

    public function index()
    {
        return view('cms.category.index');
    }

    public function store(CategoryRequest $request)
    {
        try {
            $this->categoryService->create([
                'name' => $request->name,
                'slug' => Str::slug($request->name)
            ]);

            return $this->jsonResponse->data([])->message('Successfully create category data')->success();
        } catch (\Throwable $th) {
            throw new \Exception($th->getMessage(), 500);
        }
    }

    public function update($id, CategoryRequest $request)
    {
        try {
            $this->categoryService->update($id, [
                'name' => $request->name,
                'slug' => Str::slug($request->name)
            ]);

            return $this->jsonResponse->message('Successfully update category data')->success();
        } catch (\Throwable $th) {
            throw new \Exception($th->getMessage(), 500);
        }
    }

    public function show($slug)
    {
        $category = $this->categoryService->findByColumn('slug', $slug);

        return view('cms.category.detail', compact('category'));
    }

    public function edit($id)
    {
        try {
            $category = $this->categoryService->find($id);

            return $this->jsonResponse->data($category)->message('Successfully update category data')->success();
        } catch (\Throwable $th) {
            throw new \Exception($th->getMessage(), 500);
        }
    }

    public function delete($id)
    {
        try {
            $this->categoryService->delete($id);

            return $this->jsonResponse->message('Successfully delete category data')->success();
        } catch (\Throwable $th) {
            throw new \Exception($th->getMessage(), 500);
        }
    }

    public function datatable()
    {
        $categories = $this->categoryService->get();

        return DataTables::of($categories)
            ->addIndexColumn()
            ->addColumn('action', function ($row) {
                $browseCategory = route('admin.category.show', $row->slug);

                $btn = "<div class='d-flex justify-content-center align-items-center'>";
                $btn .= "<button title='Edit' class='btn btn-warning btn-edit btn-sm mr-2' data-id='{$row->id}'><i class='fa fa-pen'></i></button>";
                $btn .= "<a href='$browseCategory' title='Detail' class='btn btn-info btn-edit btn-sm mr-2'><i class='fa fa-info-circle'></i></a>";
                $btn .= "<button data-id='{$row->id}' title='Delete' class='btn btn-danger btn-sm btn-delete'><i class='fa fa-trash'></i></button>";
                $btn .= '</div>';
                return $btn;
            })
            ->rawColumns(['action'])
            ->make(true);
    }
}

app/Http/Controllers/Website/CategoryController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use App\Services\CategoryService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    public function index()
    {
        $categories = $this->categoryService->paginate(5);
        return view('web.category.index', compact('categories'));
    }

    public function show($slug)
    {
        $category = $this->categoryService->findByColumn('slug', $slug);
        return view('web.category.detail', compact('category'));
    }
}

resources/views/cms/category/detail.blade.php
@extends('layouts.app')
@section('title')
    Laravel Blog - Category
@endsection

@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">{{ $category->name }}</h6>
        </div>
        <div class="card-body">
            <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">No</th>
                    <th scope="col">Article Name</th>
                    <th scope="col">Created At</th>
                    <th scope="col">#</th>
                  </tr>
                </thead>
                <tbody>
                    @forelse ($category->articles as $article)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $article->title }}</td>
                            <td>{{ $article->created_at->format('Y-m-d H:i:s') }}</td>
                            <td><a class="btn btn-sm btn-info" href="{{ route('admin.article.detail', $article->slug) }}" title="Go To {{ $article->title }}"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="4" align="center"><b>Articles Not Found</b></td>
                        </tr>
                    @endforelse
                </tbody>
              </table>
        </div>
    </div>
</div>
@endsection

resources/views/cms/category/index.blade.php
@extends('layouts.app')
@section('title')
    Laravel Blog - Category
@endsection

@push('css')
    <link href="{{ asset('assets') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush


@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">Category</h6>
            <button class="btn btn-info btn-create btn-sm ml-auto"><i class="fa fa-plus"></i></button>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Slug</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal-category" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form id="form-category">
            <div class="modal-body">
                <input type="hidden" name="id" id="id" class="form-control">
                <div class="form-group">
                    <label for="name">Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Please Input Category Name.." required>
                </div>
                @csrf
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary button-save" btn-type="save">Save</button>
            </div>
        </form>
      </div>
    </div>
</div>
@endsection

@push('js')
<script src="{{ asset('assets') }}/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('assets') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
@include('cms.category.script')
@endpush

resources/views/cms/category/script.blade.php
<script>
    $(document).ready(function () {
        const url = "{{ route('admin.category.datatable') }}";
        const form = $('#form-category')
        const table = $('#dataTable');
        const modal = $('#modal-category')
        const btnCreate = $('.btn-create')
        const dataTable = table.DataTable({
            processing: true,
            serverSide: true,
            ajax: url,
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                {data: 'name', name: 'name'},
                {data: 'slug', name: 'slug'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        });

        /* Functions */
        const saveCategory = (data) => {
            const url = '{{ route("admin.category.store") }}'
            $.post(url, data, (res) => {
                clearModalForm()
                dataTable.ajax.reload();

                swalSuccess('Success');
            }).fail(err => {
                switch (err.status) {
                    case 422:
                        let message = err.responseJSON.data.join('<br>')
                        swalError(message)
                        break;
                    case 500:
                        swalError('Something went wrong')
                    default:
                        break;
                }
            })
        }

        const getCategoryById = (id) => {
            let url = "{{ route('admin.category.edit', 'id') }}"
                url = url.replace('id', id)

            $.get(url, function (res) {
                modal.find('#id').val(res.data.id)
                modal.find('#name').val(res.data.name)

                modal.modal('show')
                modal.find('.modal-title').text('Edit Category')
                modal.find('.button-save').attr('data-type', 'update')
            })
        }

        const updateCategory = (id, data) => {
            let url = "{{ route('admin.category.update', 'id') }}"
                url = url.replace('id', id)

            $.ajax({
                url: url,
                method: 'PUT',
                data: data,
                success: (res) => {
                    clearModalForm()
                    dataTable.ajax.reload();

                    swalSuccess('Success');
                },
                error: (err) => {
                    switch (err.status) {
                        case 422:
                            let message = err.responseJSON.data.join('<br>')
                            swalError(message)
                            break;
                        case 500:
                            swalError('Something went wrong')
                        default:
                            break;
                    }
                }
            })
        }

        const deleteCategory = (id) => {
            let url = "{{ route('admin.category.delete', 'id') }}"
                url = url.replace('id', id)

            $.ajax({
                url: url,
                method: 'DELETE',
                data: {
                    _token: "{{ csrf_token() }}"
                },
                success: (res) => {
                    dataTable.ajax.reload();

                    swalSuccess('Success');
                },
                error: (err) => {
                    switch (err.status) {
                        case 422:
                            let message = err.responseJSON.data.join('<br>')
                            swalError(message)
                            break;
                        case 500:
                            swalError('Something went wrong')
                        default:
                            break;
                    }
                }
            })
        }

        const clearModalForm = () => {
            modal.find('.form-control').val('')
            modal.modal('hide')
        }

        btnCreate.click(function () {
            modal.find('.form-control').val('')
            modal.find('.modal-title').text('Create Category')
            modal.find('.button-save').attr('data-type', 'save')
            modal.modal('show')
        })

        form.submit(function (e) {
            e.preventDefault();

            const data = $(this).serialize()
            let id = modal.find('#id').val()

            if ($('.button-save').attr('data-type') == 'save') return saveCategory(data)

            return updateCategory(id, data)
        })

        $(document).on('click', '.btn-edit', function () {
            let self = $(this)
            let id = self.data('id')

            getCategoryById(id)
        })

        $(document).on('click', '.btn-delete', function () {
            if (confirm('Apakah anda yakin?')) {
                const id = $(this).data('id')

                deleteCategory(id);
            }
        })
    });

</script>