routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomepageController::class, 'index'])->name('homepage');

/* Website */
Route::controller(App\Http\Controllers\Website\ArticleController::class)->group(function () {
    Route::prefix('article')->name('article.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/detail/{slug}', 'show')->name('show');
    });
});

Route::controller(App\Http\Controllers\Website\CategoryController::class)->group(function () {
    Route::prefix('category')->name('category.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/detail/{slug}', 'show')->name('show');
    });
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('login/{provider}', [App\Http\Controllers\Auth\LoginController::class, 'redirectToProvider']);
Route::get('{provider}/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleProviderCallback']);

/* CMS */
Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
    /* Category */
    Route::controller(App\Http\Controllers\Admin\CategoryController::class)->middleware(['role:admin,author'])->group(function () {
        Route::prefix('category')->name('category.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/edit/{id}', 'edit')->name('edit');
            Route::get('/detail/{id}', 'show')->name('show');
            Route::get('/datatable', 'datatable')->name('datatable');
            Route::post('/', 'store')->name('store');
            Route::put('/{id}', 'update')->name('update');
            Route::delete('/delete/{id}', 'delete')->name('delete');
        });
    });

    /* Article */
    Route::controller(App\Http\Controllers\Admin\ArticleController::class)->middleware(['role:admin,author'])->group(function () {
        Route::prefix('article')->name('article.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/edit/{id}', 'edit')->name('edit');
            Route::get('/detail/{slug}', 'show')->name('detail');
            Route::get('/datatable', 'datatable')->name('datatable');
            Route::post('/', 'store')->name('store');
            Route::put('/{id}', 'update')->name('update');
            Route::delete('/delete/{id}', 'delete')->name('delete');
        });
    });

    /* User */
    Route::controller(App\Http\Controllers\Admin\UserController::class)->middleware(['role:admin'])->group(function () {
        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/detail/{slug}', 'show')->name('show');
            Route::get('/datatable', 'datatable')->name('datatable');
            Route::post('/', 'store')->name('store');
            Route::put('/{id}', 'update')->name('update');
            Route::delete('/delete/{id}', 'delete')->name('delete');
        });
    });

    Route::put('user/profile/{id}', [App\Http\Controllers\Admin\UserController::class, 'updateProfile'])->name('user.profile.update');
    Route::get('user/profile', [App\Http\Controllers\Admin\UserController::class, 'profile'])->name('user.profile');
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'slug', 'content', 'banner', 'category_id', 'created_by'];
    protected $appends = ['image_url_original', 'image_url_thumbnail'];

    public function getImageUrlOriginalAttribute()
    {
        if (is_null($this->attributes['banner'])) return url('/images/default.png');

        return url('/images/article/' . $this->attributes['banner']);
    }

    public function getImageUrlThumbnailAttribute()
    {
        if (is_null($this->attributes['banner'])) return url('/images/default-thumbnail.jpg');

        return url('/images/thumbnail/article/' . $this->attributes['banner']);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'created_by', 'id');
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Helpers\JsonResponse;
use App\Http\Requests\ArticleRequest;
use App\Services\ArticleService;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use Str;
use DataTables;

class ArticleController extends Controller
{
    protected $articleService;
    protected $jsonResponse;

    public function __construct(ArticleService $articleService, JsonResponse $jsonResponse)
    {
        $this->articleService = $articleService;
        $this->jsonResponse = $jsonResponse;
    }

    public function index()
    {
        $categories = resolve(CategoryService::class)->get();
        return view('cms.article.index', compact('categories'));
    }

    public function store(ArticleRequest $request)
    {
        try {
            $request->merge([
                'slug' => Str::slug($request->title)
            ]);
            $this->articleService->create($request->all());

            return $this->jsonResponse->data([])->message('Successfully create article data')->success();
        } catch (\Throwable $th) {
            throw new \Exception($th->getMessage(), 500);
        }
    }

    public function update($id, ArticleRequest $request)
    {
        try {
            $request->merge([
                'slug' => Str::slug($request->title)
            ]);

            $this->articleService->update($id, $request->all());

            return $this->jsonResponse->message('Successfully update article data')->success();
        } catch (\Throwable $th) {
            throw new \Exception($th->getMessage(), 500);
        }
    }

    public function edit($id)
    {
        try {
            $article = $this->articleService->find($id);

            return $this->jsonResponse->data($article)->message('Successfully update article data')->success();
        } catch (\Throwable $th) {
            throw new \Exception($th->getMessage(), 500);
        }
    }

    public function show($slug)
    {
        $article = $this->articleService->findByColumn('slug', $slug);
        return view('cms.article.detail', compact('article'));
    }

    public function delete($id)
    {
        try {
            $this->articleService->delete($id);

            return $this->jsonResponse->message('Successfully delete article data')->success();
        } catch (\Throwable $th) {
            throw new \Exception($th->getMessage(), 500);
        }
    }

    public function datatable()
    {
        $categories = $this->articleService->getByRole();

        return DataTables::of($categories)
            ->addIndexColumn()
            ->addColumn('action', function ($row) {
                $detailPage = route('admin.article.detail', $row->slug);

                $btn = "<div class='d-flex justify-content-center align-items-center'>";
                $btn .= "<button title='Edit' class='btn btn-warning btn-edit btn-sm mr-2' data-id='{$row->id}'><i class='fa fa-pen'></i></button>";
                $btn .= "<a href='$detailPage' title='Detail' class='btn btn-info btn-edit btn-sm mr-2'><i class='fa fa-info-circle'></i></a>";
                $btn .= "<button data-id='{$row->id}' title='Delete' class='btn btn-danger btn-sm btn-delete'><i class='fa fa-trash'></i></button>";
                $btn .= '</div>';
                return $btn;
            })
            ->rawColumns(['action'])
            ->make(true);
    }
}

app/Http/Controllers/Website/ArticleController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use App\Services\ArticleService;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    protected $articleService;

    public function __construct(ArticleService $articleService)
    {
        $this->articleService = $articleService;
    }

    public function index()
    {
        $articles = $this->articleService->paginate(10);
        return view('web.article.index', compact('articles'));
    }

    public function show($slug)
    {
        $article = $this->articleService->findByColumn('slug', $slug);
        return view('web.article.detail', compact('article'));
    }
}

resources/views/cms/article/detail.blade.php
@extends('layouts.app')
@section('title')
    Laravel Blog - Article
@endsection

@push('css')
    <link href="{{ asset('assets') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush


@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">{{ $article->title }}</h6>
        </div>
        <div class="card-body">
            <div class="content">
                <h6>Content : </h6>
                <p class="ml-3">{{ $article->content }}</p>
            </div>
            <div class="category">
                <h6>Category : </h6>
                <p class="ml-3">{{ $article->category->name }}</p>
            </div>
            <div class="image">
                <h6>Image</h6>
                <a target="_blank" href="{{ $article->image_url_original }}"><img src="{{ $article->image_url_original }}" alt="{{ $article->title }}"></a>
            </div>
            <hr>
            <p>Created At : {{ $article->created_at->format('Y-m-d H:i:s') }}</p>
        </div>
    </div>
</div>
@endsection

@push('js')
<script src="{{ asset('assets') }}/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('assets') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
@endpush

resources/views/cms/article/index.blade.php
@extends('layouts.app')
@section('title')
    Laravel Blog - Article
@endsection

@push('css')
    <link href="{{ asset('assets') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush


@section('content')
<div class="container-fluid">
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h5 class="alert-heading">Information</h5>
        If you're not an admin, you can only see your Article
        <button class="close" type="button" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">Article</h6>
            <button class="btn btn-info btn-create btn-sm ml-auto"><i class="fa fa-plus"></i></button>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Title</th>
                            <th>Slug</th>
                            <th>Category</th>
                            <th>Created By</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal-article" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form id="form-article">
            <div class="modal-body">
                <input type="hidden" name="id" id="id" class="form-control">
                <div class="form-group">
                    <label for="title">Title <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="Please Input article title.." required>
                </div>
                <div class="form-group">
                    <label for="content">Content <span class="text-danger">*</span></label>
                    <textarea name="content" id="content" cols="5" rows="5" class="form-control" required></textarea>
                </div>
                <div class="form-group">
                    <label for="category_id">Category <span class="text-danger">*</span></label>
                    <select name="category_id" id="category_id" class="form-control" required>
                        <option value="" selected disabled>Please Select</option>
                        @foreach ($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="banner">Banner</label>
                    <input type="file" name="banner" id="banner" class="form-control">
                </div>
                <div class="form-group image-preview">
                    <label for="">Image Preview</label>
                    <div>
                        <img src="" alt="" class="img-preview">
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary button-save" btn-type="save">Save</button>
            </div>
        </form>
      </div>
    </div>
</div>
@endsection

@push('js')
<script src="{{ asset('assets') }}/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('assets') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
@include('cms.article.script')
@endpush

resources/views/cms/article/script.blade.php
<script>
    $(document).ready(function () {
        const url = "{{ route('admin.article.datatable') }}";
        const form = $('#form-article')
        const table = $('#dataTable');
        const modal = $('#modal-article')
        const btnCreate = $('.btn-create')
        const dataTable = table.DataTable({
            processing: true,
            serverSide: true,
            ajax: url,
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                {data: 'title', name: 'title'},
                {data: 'slug', name: 'slug'},
                {data: 'category.name', name: 'category.name'},
                {
                    data: 'user.name',
                    name: 'user.name',
                    render: function (data) {
                        return data ?? '-';
                    }
                },
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        });

        /* Functions */
        const saveArticle = (data) => {
            const url = '{{ route("admin.article.store") }}'

            $.ajax({
                url: url,
                type: 'POST',
                data: data,
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                },
                success: function (res, status, xhr) {
                    clearModalForm()
                    modal.modal('hide')
                    dataTable.ajax.reload();

                    swalSuccess('Success');
                },
                error: (err, xhr) => {
                    switch (err.status) {
                        case 422:
                            let message = err.responseJSON.data.join('<br>')
                            swalError(message)
                            break;
                        case 500:
                            swalError('Something went wrong')
                        default:
                            break;
                    }
                },
                cache: false,
                contentType: false,
                processData: false
            });
        }

        const getArticleById = (id) => {
            let url = "{{ route('admin.article.edit', 'id') }}"
                url = url.replace('id', id)

            $.get(url, function (res) {
                modal.find('#id').val(res.data.id)
                modal.find('#title').val(res.data.title)
                modal.find('#content').val(res.data.content)
                modal.find('#category_id').val(res.data.category_id).trigger('change')
                modal.find('.image-preview').show()
                modal.find('.img-preview').attr('src', res.data.image_url_thumbnail)

                modal.modal('show')
                modal.find('.modal-title').text('Edit Article')
                modal.find('.button-save').attr('data-type', 'update')
            })
        }

        const updateArticle = (id, data) => {
            let url = "{{ route('admin.article.update', 'id') }}"
                url = url.replace('id', id)

            data.append('_method', 'PUT');

            $.ajax({
                url: url,
                method: 'POST',
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                },
                data: data,
                cache: false,
                contentType: false,
                processData: false,
                success: (res) => {
                    clearModalForm()
                    dataTable.ajax.reload();

                    modal.modal('hide')
                    swalSuccess('Success');
                },
                error: (err, xhr) => {
                    switch (err.status) {
                        case 422:
                            let message = err.responseJSON.data.join('<br>')
                            swalError(message)
                            break;
                        case 500:
                            swalError('Something went wrong')
                        default:
                            break;
                    }
                }
            })
        }

        const deleteArticle = (id) => {
            let url = "{{ route('admin.article.delete', 'id') }}"
                url = url.replace('id', id)

            $.ajax({
                url: url,
                method: 'DELETE',
                data: {
                    _token: "{{ csrf_token() }}"
                },
                success: (res) => {
                    dataTable.ajax.reload();

                    modal.modal('hide')
                    swalSuccess('Success');
                },
                error: (err, xhr) => {
                    switch (err.status) {
                        case 422:
                            let message = err.responseJSON.data.join('<br>')
                            swalError(message)
                            break;
                        case 500:
                            swalError('Something went wrong')
                        default:
                            break;
                    }
                }
            })
        }

        const clearModalForm = () => {
            modal.find('.form-control').val('')
        }

        btnCreate.click(function () {
            clearModalForm()
            modal.find('.modal-title').text('Create Article')
            modal.find('.button-save').attr('data-type', 'save')
            modal.find('.img-preview').attr('src', '')
            modal.find('.image-preview').hide()

            modal.modal('show')

        })

        form.submit(function (e) {
            e.preventDefault();

            const data = new FormData(this);

            let id = modal.find('#id').val()

            if ($('.button-save').attr('data-type') == 'save') return saveArticle(data)

            return updateArticle(id, data)
        })

        $(document).on('click', '.btn-edit', function () {
            let self = $(this)
            let id = self.data('id')

            getArticleById(id)
        })

        $(document).on('click', '.btn-delete', function () {
            if (confirm('Apakah anda yakin?')) {
                const id = $(this).data('id')

                deleteArticle(id);
            }
        })
    });

</script>