routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomepageController::class, 'index'])->name('homepage');

/* Website */
Route::controller(App\Http\Controllers\Website\ArticleController::class)->group(function () {
    Route::prefix('article')->name('article.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/detail/{slug}', 'show')->name('show');
    });
});

Route::controller(App\Http\Controllers\Website\CategoryController::class)->group(function () {
    Route::prefix('category')->name('category.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/detail/{slug}', 'show')->name('show');
    });
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('login/{provider}', [App\Http\Controllers\Auth\LoginController::class, 'redirectToProvider']);
Route::get('{provider}/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleProviderCallback']);

/* CMS */
Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
    /* Category */
    Route::controller(App\Http\Controllers\Admin\CategoryController::class)->middleware(['role:admin,author'])->group(function () {
        Route::prefix('category')->name('category.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/edit/{id}', 'edit')->name('edit');
            Route::get('/detail/{id}', 'show')->name('show');
            Route::get('/datatable', 'datatable')->name('datatable');
            Route::post('/', 'store')->name('store');
            Route::put('/{id}', 'update')->name('update');
            Route::delete('/delete/{id}', 'delete')->name('delete');
        });
    });

    /* Article */
    Route::controller(App\Http\Controllers\Admin\ArticleController::class)->middleware(['role:admin,author'])->group(function () {
        Route::prefix('article')->name('article.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/edit/{id}', 'edit')->name('edit');
            Route::get('/detail/{slug}', 'show')->name('detail');
            Route::get('/datatable', 'datatable')->name('datatable');
            Route::post('/', 'store')->name('store');
            Route::put('/{id}', 'update')->name('update');
            Route::delete('/delete/{id}', 'delete')->name('delete');
        });
    });

    /* User */
    Route::controller(App\Http\Controllers\Admin\UserController::class)->middleware(['role:admin'])->group(function () {
        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/detail/{slug}', 'show')->name('show');
            Route::get('/datatable', 'datatable')->name('datatable');
            Route::post('/', 'store')->name('store');
            Route::put('/{id}', 'update')->name('update');
            Route::delete('/delete/{id}', 'delete')->name('delete');
        });
    });

    Route::put('user/profile/{id}', [App\Http\Controllers\Admin\UserController::class, 'updateProfile'])->name('user.profile.update');
    Route::get('user/profile', [App\Http\Controllers\Admin\UserController::class, 'profile'])->name('user.profile');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id',
        'provider',
        'provider_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the role that owns the User
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function articles()
    {
        return $this->hasMany(Article::class, 'created_by', 'id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Helpers\JsonResponse;
use App\Http\Requests\UserRequest;
use App\Models\Role;
use App\Models\User;
use App\Services\UserService;
use DataTables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    protected $userService;
    protected $jsonResponse;

    public function __construct(UserService $userService, JsonResponse $jsonResponse)
    {
        $this->userService = $userService;
        $this->jsonResponse = $jsonResponse;
    }

    public function index()
    {
        $roles = Role::all();
        return view('cms.user.index', compact('roles'));
    }

    public function store(UserRequest $request)
    {
        try {
            $this->userService->create($request->all());

            return $this->jsonResponse->data([])->message('Successfully create category data')->success();
        } catch (\Throwable $th) {
            throw new \Exception($th->getMessage(), 500);
        }
    }

    public function update($id, UserRequest $request)
    {
        try {
            $this->userService->update($id, $request->all());

            return $this->jsonResponse->message('Successfully update category data')->success();
        } catch (\Throwable $th) {
            throw new \Exception($th->getMessage(), 500);
        }
    }

    public function show($id)
    {
        try {
            $user = $this->userService->find($id);

            return $this->jsonResponse->data($user)->message('Successfully update category data')->success();
        } catch (\Throwable $th) {
            throw new \Exception($th->getMessage(), 500);
        }
    }

    public function delete($id)
    {
        try {
            $this->userService->delete($id);

            return $this->jsonResponse->message('Successfully delete category data')->success();
        } catch (\Throwable $th) {
            throw new \Exception($th->getMessage(), 500);
        }
    }

    public function datatable()
    {
        $users = $this->userService->get();

        return DataTables::of($users)
            ->addIndexColumn()
            ->addColumn('action', function ($row) {
                $disabled = '';
                if ($row->id == userLogin()->id) {
                    $disabled = 'disabled';
                }

                $btn = "<div class='d-flex justify-content-center align-items-center'>";
                $btn .= "<button class='btn btn-warning btn-edit btn-sm mr-2' data-id='{$row->id}'><i class='fa fa-pen' ></i></button>";
                $btn .= "<button data-id='{$row->id}' class='btn btn-danger btn-sm btn-delete' $disabled><i class='fa fa-trash'></i></button>";
                $btn .= '</div>';
                return $btn;
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function profile()
    {
        $profile = userLogin();
        return view('cms.user.profile', compact('profile'));
    }

    public function updateProfile($id, Request $request)
    {
        try {
            $validator = Validator::make($request->all(), [
                'name' => 'required',
                'email' => 'required|email|unique:users,email,' . $id,
                'password' => 'nullable|confirmed|min:6|required_with:old_password'
            ]);

            if ($validator->fails()) return back()->with('error', $validator->errors()->first());

            $oldPassword = userLogin()->password;

            if (!is_null($request['old_password']) && !Hash::check($request['old_password'], $oldPassword)) return back()->with('error', 'Old password not match');

            $this->userService->update($id, $request->all());

            return back()->with('success', 'Successfully update profile');
        } catch (\Throwable $th) {
            return back()->with('error', 'Internal Server Error');
        }
    }
}

resources/views/cms/user/index.blade.php
@extends('layouts.app')
@section('title')
    Laravel Blog - User
@endsection

@push('css')
    <link href="{{ asset('assets') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush


@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">User</h6>
            <button class="btn btn-info btn-create btn-sm ml-auto"><i class="fa fa-plus"></i></button>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal-user" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form id="form-user">
            <div class="modal-body">
                <input type="hidden" name="id" id="id" class="form-control">
                @csrf
                <div class="form-group">
                    <label for="name">Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Please Input User Fullname.." required>
                </div>
                <div class="form-group">
                    <label for="email">Email <span class="text-danger">*</span></label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Please Input User Email.." required>
                </div>
                <div class="form-group">
                    <label for="role_id">Role <span class="text-danger">*</span></label>
                    <select name="role_id" id="role_id" class="form-control" required>
                        <option value="" selected disabled>Please Select</option>
                        @foreach ($roles as $role)
                            <option value="{{ $role->id }}">{{ $role->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group form-password">
                    <label for="password">Password <span class="text-danger">*</span></label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Please Input User Password.." required>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary button-save" btn-type="save">Save</button>
            </div>
        </form>
      </div>
    </div>
</div>
@endsection

@push('js')
<script src="{{ asset('assets') }}/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('assets') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
@include('cms.user.script')
@endpush

resources/views/cms/user/profile.blade.php
@extends('layouts.app')
@section('title')
    Laravel Blog - Profile {{ userLogin()->name }}
@endsection

@push('css')
    <link href="{{ asset('assets') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush


@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="card shadow mb-4">
        <div class="card-header">
            <h6><b>Profile {{ $profile->name }}</b></h6>
        </div>
        <div class="card-body">
            <form method="POST" action="{{ route('admin.user.profile.update', $profile->id) }}">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                          <label for="name">Full Name <span class="text-danger">*</span></label>
                          <input type="text" class="form-control" id="name" name="name" placeholder="Enter Full Name" value="{{ $profile->name }}" required>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="email">Email address <span class="text-danger">*</span></label>
                            <input type="email" class="form-control" name="email" id="email" aria-describedby="emailHelp" placeholder="Enter email" value="{{ $profile->email }}" required>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                          <label for="old_password">Old Password</label>
                          <input type="password" class="form-control" id="old_password" name="old_password" placeholder="Enter Old Password" @if (is_null($profile->password)) readonly @endif>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                          <label for="new_password">Password</label>
                          <input type="password" class="form-control" id="new_password" name="password" placeholder="Enter New Password">
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                          <label for="confirm_password">Confirm Password</label>
                          <input type="password" class="form-control" id="confirm_password" name="password_confirmation" placeholder="Enter Old Password">
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>


@endsection

@push('js')
<script src="{{ asset('assets') }}/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('assets') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
@include('cms.user.script')
@endpush

resources/views/cms/user/script.blade.php
<script>
    $(document).ready(function () {
        const url = "{{ route('admin.user.datatable') }}";
        const form = $('#form-user')
        const table = $('#dataTable');
        const modal = $('#modal-user')
        const btnCreate = $('.btn-create')
        const dataTable = table.DataTable({
            processing: true,
            serverSide: true,
            ajax: url,
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                {data: 'name', name: 'name'},
                {data: 'email', name: 'email'},
                {data: 'role.name', name: 'role.name'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        });

        /* Functions */
        const saveUser = (data) => {
            const url = '{{ route("admin.user.store") }}'
            $.post(url, data, (res) => {
                clearModalForm()
                dataTable.ajax.reload();

                swalSuccess('Success');
            }).fail(err => {
                switch (err.status) {
                    case 422:
                        let message = err.responseJSON.data.join('<br>')
                        swalError(message)
                        break;
                    case 500:
                        swalError('Something went wrong')
                    default:
                        break;
                }
            })
        }

        const getUserById = (id) => {
            let url = "{{ route('admin.user.show', 'id') }}"
                url = url.replace('id', id)

            $.get(url, function (res) {
                modal.find('#id').val(res.data.id)
                modal.find('#name').val(res.data.name)
                modal.find('#email').val(res.data.email)
                modal.find('#role_id').val(res.data.role_id).trigger('change')
                modal.find('.form-password').hide()

                modal.modal('show')
                modal.find('.modal-title').text('Edit User')
                modal.find('.button-save').attr('data-type', 'update')
            })
        }

        const updateUser = (id, data) => {
            let url = "{{ route('admin.user.update', 'id') }}"
                url = url.replace('id', id)

            $.ajax({
                url: url,
                method: 'PUT',
                data: data,
                success: (res) => {
                    clearModalForm()
                    dataTable.ajax.reload();

                    swalSuccess('Success');
                },
                error: (err) => {
                    switch (err.status) {
                        case 422:
                            let message = err.responseJSON.data.join('<br>')
                            swalError(message)
                            break;
                        case 500:
                            swalError('Something went wrong')
                        default:
                            break;
                    }
                }
            })
        }

        const deleteUser = (id) => {
            let url = "{{ route('admin.user.delete', 'id') }}"
                url = url.replace('id', id)

            $.ajax({
                url: url,
                method: 'DELETE',
                data: {
                    _token: "{{ csrf_token() }}"
                },
                success: (res) => {
                    dataTable.ajax.reload();

                    swalSuccess('Success');
                },
                error: (err) => {
                    switch (err.status) {
                        case 422:
                            let message = err.responseJSON.data.join('<br>')
                            swalError(message)
                            break;
                        case 500:
                            swalError('Something went wrong')
                        default:
                            break;
                    }
                }
            })
        }

        const clearModalForm = () => {
            modal.find('.form-control').val('')
            modal.modal('hide')
        }

        btnCreate.click(function () {
            modal.find('.form-control').val('')
            modal.find('.modal-title').text('Create User')
            modal.find('.button-save').attr('data-type', 'save')
            modal.find('.form-password').show()
            modal.modal('show')
        })

        form.submit(function (e) {
            e.preventDefault();

            const data = $(this).serialize()
            let id = modal.find('#id').val()

            if ($('.button-save').attr('data-type') == 'save') return saveUser(data)

            return updateUser(id, data)
        })

        $(document).on('click', '.btn-edit', function () {
            let self = $(this)
            let id = self.data('id')

            getUserById(id)
        })

        $(document).on('click', '.btn-delete', function () {
            if (confirm('Apakah anda yakin?')) {
                const id = $(this).data('id')

                deleteUser(id);
            }
        })
    });

</script>