routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomepageController::class, 'index'])->name('homepage');

/* Website */
Route::controller(App\Http\Controllers\Website\ArticleController::class)->group(function () {
    Route::prefix('article')->name('article.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/detail/{slug}', 'show')->name('show');
    });
});

Route::controller(App\Http\Controllers\Website\CategoryController::class)->group(function () {
    Route::prefix('category')->name('category.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/detail/{slug}', 'show')->name('show');
    });
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('login/{provider}', [App\Http\Controllers\Auth\LoginController::class, 'redirectToProvider']);
Route::get('{provider}/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleProviderCallback']);

/* CMS */
Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
    /* Category */
    Route::controller(App\Http\Controllers\Admin\CategoryController::class)->middleware(['role:admin,author'])->group(function () {
        Route::prefix('category')->name('category.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/edit/{id}', 'edit')->name('edit');
            Route::get('/detail/{id}', 'show')->name('show');
            Route::get('/datatable', 'datatable')->name('datatable');
            Route::post('/', 'store')->name('store');
            Route::put('/{id}', 'update')->name('update');
            Route::delete('/delete/{id}', 'delete')->name('delete');
        });
    });

    /* Article */
    Route::controller(App\Http\Controllers\Admin\ArticleController::class)->middleware(['role:admin,author'])->group(function () {
        Route::prefix('article')->name('article.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/edit/{id}', 'edit')->name('edit');
            Route::get('/detail/{slug}', 'show')->name('detail');
            Route::get('/datatable', 'datatable')->name('datatable');
            Route::post('/', 'store')->name('store');
            Route::put('/{id}', 'update')->name('update');
            Route::delete('/delete/{id}', 'delete')->name('delete');
        });
    });

    /* User */
    Route::controller(App\Http\Controllers\Admin\UserController::class)->middleware(['role:admin'])->group(function () {
        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/detail/{slug}', 'show')->name('show');
            Route::get('/datatable', 'datatable')->name('datatable');
            Route::post('/', 'store')->name('store');
            Route::put('/{id}', 'update')->name('update');
            Route::delete('/delete/{id}', 'delete')->name('delete');
        });
    });

    Route::put('user/profile/{id}', [App\Http\Controllers\Admin\UserController::class, 'updateProfile'])->name('user.profile.update');
    Route::get('user/profile', [App\Http\Controllers\Admin\UserController::class, 'profile'])->name('user.profile');
});

resources/views/layouts/alert.blade.php
@if ($message = Session::get('success'))
<div class="container-fluid">
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <h5 class="alert-heading">Success !</h5>
        {{ $message }}
        <button class="close" type="button" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
</div>
@endif

@if ($message = Session::get('error'))
<div class="container-fluid">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h5 class="alert-heading">Error !</h5>
        {{ $message }}
        <button class="close" type="button" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
</div>
@endif

@if ($message = Session::get('warning'))
<div class="container-fluid">
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h5 class="alert-heading">Warning !</h5>
        {{ $message }}
        <button class="close" type="button" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
</div>
@endif

@if ($message = Session::get('info'))
<div class="container-fluid">
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <h5 class="alert-heading">Info !</h5>
        {{ $message }}
        <button class="close" type="button" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
</div>
@endif

@if ($errors->any())
<div class="m-3 alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    {{ $errors->first() }}
</div>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('title', 'Laravel Blog')</title>

    @include('layouts.css')

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        @include('layouts.sidebar')

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                @include('layouts.navbar')
                <!-- End of Topbar -->
                @include('layouts.alert')

                <!-- Begin Page Content -->
                @yield('content')
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; SB Admin {{ date('Y') }}</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    @include('layouts.script')

</body>

</html>

resources/views/layouts/css.blade.php
<!-- Custom fonts for this template-->
<link href="{{ asset('assets') }}/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
<link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{{ asset('assets') }}/css/sb-admin-2.min.css" rel="stylesheet">
<link href="{{ asset('assets') }}/vendor/toastr/toastr.min.css" rel="stylesheet">
<style>
    .select2 {
        width: 100% !important;
    }
    .select2-selection {
        height: 37px !important;
    }
    .select2-selection__rendered {
        line-height: 37px !important;
    }
    .select2-selection__arrow {
        top: 5px !important;
    }
</style>
@stack('css')

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->

        <!-- Nav Item - Messages -->
        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"></span>
                <img class="img-profile rounded-circle"
                    src="{{ asset('assets') }}/img/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{ route('admin.user.profile') }}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                    <i class="fas fa-sm fa-fw fa-sign-out-alt mr-2"></i>
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </div>
        </li>

    </ul>

</nav>

resources/views/layouts/script.blade.php
<!-- Bootstrap core JavaScript-->
<script src="{{ asset('assets') }}/vendor/jquery/jquery.min.js"></script>
<script src="{{ asset('assets') }}/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="{{ asset('assets') }}/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="{{ asset('assets') }}/js/sb-admin-2.min.js"></script>

<!-- Page level plugins -->
<script src="{{ asset('assets') }}/vendor/chart.js/Chart.min.js"></script>
<script src="{{ asset('assets') }}/vendor/toastr/toastr.min.js"></script>
<script src="{{ asset('assets/vendor/pusher/pusher.min.js') }}"></script>
<script src="{{ asset('assets/vendor/sweetalert2/sweetalert.min.js') }}"></script>
<script>
    const loader = () => {
        Swal.fire({
            title: 'Please Wait !',
            allowOutsideClick: false,
            showConfirmButton: false,
            didOpen: () => {
                Swal.showLoading()
            },
        });
    }
    const closeLoader = () => Swal.close()

    const swalSuccess = message => {
        Swal.fire({
            icon: 'success',
            title: message,
            showConfirmButton: false,
            timer: 1500
        })
    }

    const swalError = message => {
        Swal.fire({
            icon: 'error',
            title: message,
            showConfirmButton: false,
            timer: 1500
        })
    }
</script>
@stack('js')

resources/views/layouts/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('home') }}">
        <div class="sidebar-brand-icon rotate-n-15">
        </div>
        <div class="sidebar-brand-text mx-3">Laravel Blog</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item @if (Request::is('home')) active @endif">
        <a class=" nav-link" href="{{ route('home') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

    <li class="nav-item @if (Request::is('admin/article*')) active @endif">
        <a class=" nav-link" href="{{ route('admin.article.index') }}">
        <i class="fas fa-fw fa-newspaper"></i>
        <span>Article</span></a>
    </li>

    <li class="nav-item @if (Request::is('admin/category*')) active @endif">
        <a class=" nav-link" href="{{ route('admin.category.index') }}">
        <i class="fas fa-fw fa-list-alt"></i>
        <span>Category</span></a>
    </li>
    @if (isAdmin())
    <li class="nav-item @if (Request::is('admin/user*')) active @endif">
        <a class=" nav-link" href="{{ route('admin.user.index') }}">
        <i class="fas fa-fw fa-user"></i>
        <span>User</span></a>
    </li>
    @endif

    <!-- Divider -->
    <hr class="sidebar-divider">
    <li class="nav-item">
        <a class=" nav-link" href="{{ route('homepage') }}">
        <i class="fas fa-fw fa-arrow-right"></i>
        <span>Go To Website</span></a>
    </li>

</ul>
<!-- End of Sidebar -->